dataset: data/floodgate/ds2020to2024
base_model: Qwen/Qwen3-0.6B-Base
sft_config:
    output_dir: data/train/qwen3-0.6b-t64-winner
    num_train_epochs: 1
    gradient_accumulation_steps: 2
    per_device_train_batch_size: 8
    save_strategy: steps
    logging_steps: 100
    save_steps: 100000
    lr_scheduler_type: constant
    save_total_limit: 20
    bf16: true
    max_seq_length: 256
formatter:
  n_think: 64
  append_winner: true
